### ISSUE TITLE
erreur du fichier version txt

### ISSUE THREAD

**Issue by mascotte88** [OGSteam/mod-gestionmod#4]
04/10/2018 14:08:33 : [admin][mod_erreur] Emina mod/gestionmod/version.txt mal formé

**Comment by mascotte88** [comment]
> 04/10/2018 14:08:33 : [admin][mod_erreur] Emina mod/gestionmod/version.txt mal formé

**Comment by darknoon29** [comment]
Dupliqué avec #2
